<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'full_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'table' => array( 'connId' => 'reservation_at_localhost',
'table' => 'users' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'YMsrNU4prfMIWUcz1HfN',
'JWTSecret' => '64irziLKUb5TZy6KHUZH' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'registerPage' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( 'bookings' => array( 'mainOwnerIDField' => 'id',
'securityOption' => 0,
'userOwnerIDField' => 'id' ),
'halls' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'lookup_references' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'reservation_at_localhost',
'table' => 'reservation_audit' ),
'lockingTable' => array( 'connId' => 'reservation_at_localhost',
'table' => '˂Create new˃' ),
'tables' => array( 'bookings' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'halls' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'lookup_references' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'reservation',
'loginDataSource' => 'users',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'reservation',
'dpTableConnId' => 'reservation_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'full_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'table' => array( 'connId' => 'reservation_at_localhost',
'table' => 'users' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>